version: "3"
services:

  proxy:
    image: jardilio/devops-in-a-box-proxy:latest
    build: ./proxy
    container_name: proxy
    restart: always
    env_file: ./.env
    environment:
      # below required variances between compose and k8s, kompose doesn't pick this up do to env_file (bug)
      NGINX_RESOLVER: 127.0.0.11
      NGINX_SERVICE_SUFFIX: ""
    ports:
      - 80:80
      - 443:443
    labels:
      kompose.service.type: LoadBalancer

  openldap:
    image: jardilio/devops-in-a-box-openldap:latest
    build: ./openldap
    container_name: openldap
    restart: always
    volumes:
      - openldap-data:/var/lib/ldap
      - openldap-config:/etc/ldap/slapd.d
    env_file: ./.env
    ports:
      - 389
  
  openldap-admin:
    image: osixia/phpldapadmin:0.7.0
    container_name: openldap-admin
    restart: always
    environment: 
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: 'false'
      PHPLDAPADMIN_SERVER_PATH: /openldap
    depends_on:
      - proxy
      - openldap
    ports:
      - 80

  gitlab:
    image: jardilio/devops-in-a-box-gitlab:latest
    build: ./gitlab
    container_name: gitlab
    restart: always
    volumes:
      - gitlab-data:/var/opt/gitlab
      - gitlab-logs:/var/log/gitlab
    env_file: ./.env
    depends_on:
      - openldap
      - proxy
    ports:
      - 80

  jenkins:
    image: jardilio/devops-in-a-box-jenkins:latest
    build: ./jenkins
    container_name: jenkins
    restart: always
    volumes:
      - jenkins-data:/var/jenkins_home
      #- jenkins-workspace:/var/jenkins_home/workspace
    env_file: ./.env
    depends_on:
      - proxy
      - openldap
      #- jenkins-docker-agent
    ports:
      - 8080

  # TODO: share volume and mount docker in k8s
  # jenkins-docker-agent:
  #   image: jardilio/devops-in-a-box-jenkins-docker-agent:latest
  #   build: ./jenkins-docker-agent
  #   restart: always
  #   volumes:
  #     - jenkins-workspace:/workspace
  #     - jenkins-data:/var/jenkins_home
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   env_file: ./.env
  #   privileged: true
  #   deploy:
  #     mode: replicated
  #     replicas: 2

volumes:
  openldap-data:
  openldap-config:
  gitlab-data:
  gitlab-logs:
  jenkins-data:
  jenkins-workspace: