version: "3"
services:

  proxy:
    image: jardilio/devops-in-a-box-proxy:latest
    build: ./proxy
    container_name: proxy
    restart: always
    environment:
      NGINX_SERVER_NAME: $DOS_HOSTNAME
      NGINX_PORT: $NGINX_PORT
      NGINX_RESOLVER: $NGINX_RESOLVER
      NGINX_SERVICE_SUFFIX: $NGINX_SERVICE_SUFFIX
    ports:
      - 80:80
      - 443:443
    labels:
      kompose.service.type: LoadBalancer

  openldap:
    image: jardilio/devops-in-a-box-openldap:latest
    build: ./openldap
    container_name: openldap
    restart: always
    command: --loglevel debug
    volumes:
      - openldap-data:/var/lib/ldap
    environment:
      LDAP_ORGANISATION: $LDAP_ORGANISATION
      LDAP_DOMAIN: $LDAP_DOMAIN
      LDAP_BASE_DN: $LDAP_BASE_DN
      LDAP_READONLY_USER_PASSWORD: $LDAP_READONLY_USER_PASSWORD
    ports:
      - 389
  
  openldap-admin:
    image: osixia/phpldapadmin:0.7.0
    container_name: openldap-admin
    restart: always
    environment: 
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: 'false'
      PHPLDAPADMIN_SERVER_PATH: /openldap
    depends_on:
      - proxy
      - openldap
    ports:
      - 80

  # TODO: external smtp server

  gitlab:
    image: jardilio/devops-in-a-box-gitlab:latest
    build: ./gitlab
    container_name: gitlab
    restart: always
    volumes:
      - gitlab-data:/var/opt/gitlab
      - gitlab-logs:/var/log/gitlab
    environment:
      LDAP_BASE_DN: $LDAP_BASE_DN
      LDAP_READONLY_USER_PASSWORD: $LDAP_READONLY_USER_PASSWORD
      GITLAB_TOKEN: $GITLAB_TOKEN
      GITLAB_URL: $DOS_PROTOCOL://$DOS_HOSTNAME/gitlab
      MATTERMOST_URL: $DOS_PROTOCOL://$DOS_HOSTNAME/mattermost
    depends_on:
      - openldap
      - proxy
    ports:
      - 80

  # TODO: external postgres and redis for gitlab

  jenkins:
    image: jardilio/devops-in-a-box-jenkins:latest
    build: ./jenkins
    container_name: jenkins
    restart: always
    volumes:
      - jenkins-data:/var/jenkins_home
    environment:
      LDAP_BASE_DN: $LDAP_BASE_DN
      LDAP_READONLY_USER_PASSWORD: $LDAP_READONLY_USER_PASSWORD
      GITLAB_TOKEN: $GITLAB_TOKEN
      GITLAB_URL: $DOS_PROTOCOL://$DOS_HOSTNAME/gitlab
      JENKINS_URL: $DOS_PROTOCOL://$DOS_HOSTNAME/jenkins
    depends_on:
      - proxy
      - openldap
      - jenkins-docker-agent
    ports:
      - 8080
      - 50000

  jenkins-docker-agent:
    image: jardilio/devops-in-a-box-jenkins-docker-agent:latest
    build: ./jenkins-docker-agent
    restart: always
    privileged: true
    environment:
      JENKINS_AGENT_PASSWORD: $DOS_SYSTEM_USER_PASSWORD
    deploy:
      mode: replicated
      replicas: 2
    # TODO: volume mapping for jenkins workspace share and docker image cache

volumes:
  openldap-data:
  gitlab-data:
  gitlab-logs:
  jenkins-data: