version: "3"
services:

  proxy:
    image: jardilio/devops-in-a-box-proxy:latest
    build: ./proxy
    container_name: proxy
    restart: always
    environment:
      NGINX_SERVER_NAME: $NGINX_SERVER_NAME
      NGINX_PORT: $NGINX_PORT
      NGINX_RESOLVER: $NGINX_RESOLVER
      NGINX_SERVICE_SUFFIX: $NGINX_SERVICE_SUFFIX
    ports:
      - 80:80
      - 443:443
    labels:
      kompose.service.type: LoadBalancer

  openldap:
    image: jardilio/devops-in-a-box-openldap:latest
    build: ./openldap
    container_name: openldap
    restart: always
    command: --loglevel debug
    volumes:
      - openldap-data:/var/lib/ldap
    environment:
      LDAP_ORGANISATION: $LDAP_ORGANISATION
      LDAP_DOMAIN: $LDAP_DOMAIN
      LDAP_BASE_DN: $LDAP_BASE_DN
      LDAP_READONLY_USER_PASSWORD: $LDAP_READONLY_USER_PASSWORD
    ports:
      - 389
  
  openldap-admin:
    image: osixia/phpldapadmin:0.7.0
    container_name: openldap-admin
    restart: always
    environment: 
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: 'false'
      PHPLDAPADMIN_SERVER_PATH: /openldap
    depends_on:
      - proxy
      - openldap
    ports:
      - 80

  gitlab:
    image: jardilio/devops-in-a-box-gitlab:latest
    build: ./gitlab
    container_name: gitlab
    restart: always
    volumes:
      - gitlab-data:/var/opt/gitlab
      - gitlab-logs:/var/log/gitlab
    environment:
      LDAP_BASE_DN: $LDAP_BASE_DN
      LDAP_READONLY_USER_PASSWORD: $LDAP_READONLY_USER_PASSWORD
      GITLAB_URL: $GITLAB_URL
    depends_on:
      - openldap
      - proxy
    ports:
      - 80

  jenkins:
    image: jardilio/devops-in-a-box-jenkins:latest
    build: ./jenkins
    container_name: jenkins
    restart: always
    volumes:
      - jenkins-data:/var/jenkins_home
    environment:
      LDAP_BASE_DN: $LDAP_BASE_DN
      LDAP_READONLY_USER_PASSWORD: $LDAP_READONLY_USER_PASSWORD
      GITLAB_URL: $GITLAB_URL
      JENKINS_URL: $JENKINS_URL
    depends_on:
      - proxy
      - openldap
      - jenkins-docker-agent
    ports:
      - 8080
      - 50000

  jenkins-docker-agent:
    image: jardilio/devops-in-a-box-jenkins-docker-agent:latest
    build: ./jenkins-docker-agent
    restart: always
    privileged: true
    environment:
      JENKINS_AGENT_PASSWORD: $DOS_SYSTEM_USER_PASSWORD
      JENKINS_AGENT_NUM_EXECUTORS: $JENKINS_AGENT_NUM_EXECUTORS
    deploy:
      mode: replicated
      replicas: 2

  rocketchat:
    image: rocket.chat:0.66
    container_name: rocketchat
    restart: always
    environment:
      ROOT_URL: $ROCKETCHAT_URL
      MONGO_URL: mongodb://rocketchat-database:27017/rocketchat
      OVERWRITE_SETTING_LDAP_BaseDN: $LDAP_BASE_DN
      OVERWRITE_SETTING_LDAP_Authentication_UserDN: cn=$LDAP_READONLY_USER_USERNAME,dc=devops
      OVERWRITE_SETTING_LDAP_User_Search_Filter: (memberOf=cn=devops-user,ou=roles,$LDAP_BASE_DN)
      OVERWRITE_SETTING_LDAP_Enable: 'true'
      OVERWRITE_SETTING_LDAP_Login_Fallback: 'true'
      OVERWRITE_SETTING_LDAP_Host: openldap
      OVERWRITE_SETTING_LDAP_Authentication: 'true'
      OVERWRITE_SETTING_LDAP_Username_Field: '#{cn}'
      OVERWRITE_SETTING_LDAP_Merge_Existing_Users: 'true'
      OVERWRITE_SETTING_LDAP_Sync_User_Data: 'true'
      OVERWRITE_SETTING_LDAP_Sync_User_Avatar: 'false'
      OVERWRITE_SETTING_LDAP_User_Search_Field: uid
      OVERWRITE_SETTING_LDAP_User_Search_Scope: ''
      OVERWRITE_SETTING_LDAP_Unique_Identifier_Field: objectGUID
      OVERWRITE_SETTING_LDAP_User_Search_Field: uid
      OVERWRITE_SETTING_Accounts_RegistrationForm: Disabled
    depends_on:
      - proxy
      - openldap
      - rocketchat-database
    ports:
      - 3000

  rocketchat-database:
    image: mongo:3
    container_name: rocketchat-database
    restart: always
    volumes:
      - rocketchat-data:/data/db
    ports:
      - 27017
    command: mongod --smallfiles

volumes:
  openldap-data:
  gitlab-data:
  gitlab-logs:
  jenkins-data:
  rocketchat-uploads:
  rocketchat-data: