apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f /workspace/docker-compose.yml convert
    kompose.version: 1.15.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: jenkins
  name: jenkins
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: jenkins
status:
  loadBalancer: {}
