apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f /workspace/docker-compose.yml convert
    kompose.version: 1.15.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: openldap-admin
  name: openldap-admin
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: openldap-admin
    spec:
      containers:
      - env:
        - name: PHPLDAPADMIN_HTTPS
          value: "false"
        - name: PHPLDAPADMIN_LDAP_HOSTS
          value: openldap
        - name: PHPLDAPADMIN_SERVER_PATH
          value: /openldap
        imagePullPolicy: Always
        image: osixia/phpldapadmin:0.7.0
        name: openldap-admin
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
