apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f /workspace/docker-compose.yml convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.15.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: proxy
  name: proxy
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: proxy
    spec:
      containers:
      - env:
        - name: DOS_SYSTEM_USER_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: DOS_SYSTEM_USER_PASSWORD
              name: proxy-env
        - name: GITLAB_API_KEY
          valueFrom:
            configMapKeyRef:
              key: GITLAB_API_KEY
              name: proxy-env
        - name: GITLAB_URL
          valueFrom:
            configMapKeyRef:
              key: GITLAB_URL
              name: proxy-env
        - name: JENKINS_URL
          valueFrom:
            configMapKeyRef:
              key: JENKINS_URL
              name: proxy-env
        - name: LDAP_BASE_DN
          valueFrom:
            configMapKeyRef:
              key: LDAP_BASE_DN
              name: proxy-env
        - name: LDAP_DOMAIN
          valueFrom:
            configMapKeyRef:
              key: LDAP_DOMAIN
              name: proxy-env
        - name: LDAP_ORGANISATION
          valueFrom:
            configMapKeyRef:
              key: LDAP_ORGANISATION
              name: proxy-env
        - name: LDAP_READONLY_USER_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: LDAP_READONLY_USER_PASSWORD
              name: proxy-env
        - name: NGINX_PORT
          valueFrom:
            configMapKeyRef:
              key: NGINX_PORT
              name: proxy-env
        - name: NGINX_RESOLVER
          valueFrom:
            configMapKeyRef:
              key: NGINX_RESOLVER
              name: proxy-env
        - name: NGINX_SERVER_NAME
          valueFrom:
            configMapKeyRef:
              key: NGINX_SERVER_NAME
              name: proxy-env
        - name: NGINX_SERVICE_SUFFIX
          valueFrom:
            configMapKeyRef:
              key: NGINX_SERVICE_SUFFIX
              name: proxy-env
        imagePullPolicy: Always
        image: jardilio/devops-in-a-box-proxy:latest
        name: proxy
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
      restartPolicy: Always
status: {}
