version: "3"
services:

  k8s:
    image: femtopixel/kompose
    working_dir: /workspace/deploy/k8s
    entrypoint: ["sh", "build.sh"]
    volumes:
      - ../:/workspace

  gcp:
    image: google/cloud-sdk
    entrypoint: ["sh", "./deploy/gcp/deploy.sh"]
    env_file: ./gcp/.env
    working_dir: /workspace
    volumes:
      - ../:/workspace
    depends_on:
      - k8s

  aws:
    build: ./aws
    entrypoint: ["sh", "./deploy/aws/deploy.sh"]
    env_file: ./aws/.env
    working_dir: /workspace
    volumes:
      - ../:/workspace
    depends_on:
      - k8s